// react-todo-app/src/App.js
import React, { useState } from 'react';
import Container from 'react-bootstrap/Container'
import './App.css';

import TodoForm from './components/TodoForm'
import TodoList from './components/TodoList'

function App() {
  const [todos, setTodos] = useState([]);
  const [nextIndex, setNextIndex] = useState(0);


  const addTodo = (todoText) => {
    const todo = { id: nextIndex, text: todoText, completed: false };

    setTodos([...todos, todo]);
    setNextIndex(nextIndex + 1);
  };

  const removeTodo = (id) => {
    setTodos(
      todos.filter(todo => {
        return todo.id !== id;
      })
    );
  };

  return (
    <Container className="App">
      <h2>React Todo App</h2>
      <TodoForm addTodo={addTodo} />
      <TodoList todos={todos} removeTodo={removeTodo} />
    </Container>
  );
}

export default App;

// vue-todo-app/src/App.vue
<template>
  <b-container id="app">
    <h1>{{ message }}</h1>
    <TodoForm :addTodo="addTodo" />
    <TodoList :todos="todos" :removeTodo="removeTodo" />
  </b-container>
</template>

<script>
import TodoForm from "./components/TodoForm";
import TodoList from "./components/TodoList";

export default {
  name: "app",
  data: function() {
    return {
      message: "Vue Todo App",
      todos: [],
      nextIndex: 0
    };
  },
  methods: {
    addTodo(todoText) {
      this.todos.push({ id: this.nextIndex, text: todoText, completed: false });
      this.nextIndex++;
    },
    removeTodo(id) {
      this.todos = this.todos.filter(todo => {
        return todo.id !== id;
      });
    }
  },
  components: {
    TodoForm: TodoForm,
    TodoList: TodoList
  }
};
</script>

<style>
</style>
