// vue-todo-app/src/components/TodoList.vue
<template>
  <div id="TodoList" class="mt-4">
    <h2>TodoList</h2>
    <b-list-group>
      <Todo
        v-for="todo in todos"
        :key="todo.id"
        :todo="todo"
        v-on:remove-todo="removeTodo(todo.id)"
      />
    </b-list-group>
  </div>
</template>

<script>
import Todo from "./Todo";

export default {
  name: "TodoList",
  props: ["todos", "removeTodo"],
  components: { Todo: Todo },
  methods: {}
};
</script>

<style>
</style>

// react-todo-app/src/components/TodoList.js
import React from 'react';
import ListGroup from 'react-bootstrap/ListGroup';

import Todo from './Todo'


function TodoList({ todos, removeTodo }) {
  const todoList = todos.map((todo, index) => {
    return <Todo todo={todo} key={index} removeTodo={removeTodo} />
  });

  return (
    <div className="TodoList">
      <h2>TodoList</h2>
      <ListGroup>
        {todoList}
      </ListGroup>
    </div>
  );
}

export default TodoList;
