// vue-todo-app/src/components/TodoForm.vue
<template>
  <b-form id="TodoForm" @submit.prevent="onSubmit">
    <label id="label-1" label-for="input-todo" class="sr-only">Enter a Todo</label>
    <b-row>
      <b-col md="10">
        <b-form-input
          id="input-todo"
          class="w-100"
          v-model="todoText"
          type="text"
          required
          placeholder="Enter your todo"
        ></b-form-input>
      </b-col>
      <b-col md="2">
        <b-button type="submit" variant="primary">Submit</b-button>
      </b-col>
    </b-row>
  </b-form>
</template>

<script>
export default {
  name: "TodoForm",
  props: ["addTodo"],
  data() {
    return {
      todoText: ""
    };
  },
  components: {},
  methods: {
    onSubmit() {
      if (this.todoText.length > 0) {
        this.addTodo(this.todoText);
        this.todoText = "";
      } else {
        alert("Todo text must not be blank");
      }
    }
  }
};
</script>

<style>
b-form-input {
  margin: 10px;
}

b-button {
  margin: 10px;
}
</style>

// react-todo-app/src/components/TodoForm.js
import React, { useState } from 'react';
import Form from 'react-bootstrap/Form';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';

function TodoForm({ addTodo }) {
  const [todoText, setTodoText] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    addTodo(todoText);
    setTodoText('');
  };

  return (
    <div className="TodoForm">
      <Form onSubmit={handleSubmit}>
        <Form.Row>
          <Form.Label column sm={2} srOnly>
            Enter a Todo
    </Form.Label>
          <Col sm={10}>
            <Form.Control
              type="text"
              placeholder="Enter a Todo"
              value={todoText}
              onChange={(e) => setTodoText(e.target.value)}
            />
          </Col>
          <Col sm={2}>
            <Button type="submit">Submit</Button>
          </Col>
        </Form.Row>
      </Form>
    </div>
  );
}

export default TodoForm;
