// react-todo-app/src/components/Todo.js
import React, { useState } from 'react';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';
import ListGroup from 'react-bootstrap/ListGroup';

import '../App.css';


function Todo({ todo, removeTodo }) {
  const [todoItem, setTodoItem] = useState(todo);

  const toggleDone = () => {
    setTodoItem({
      ...todoItem,
      "completed": !todoItem.completed
    });
  }

  return (
    <ListGroup.Item className="Todo">
      <Row>
        <Col sm={8}><p className={todoItem.completed ? "isDone" : ""}>{todoItem.text}</p></Col>
        <Col sm={2}><Button onClick={toggleDone}>{todoItem.completed ? "unDone" : "Done"}</Button></Col>
        <Col sm={2}><Button onClick={() => removeTodo(todoItem.id)}>Delete</Button></Col>
      </Row>
    </ListGroup.Item>
  );
}

export default Todo;

// vue-todo-app/src/components/Todo.vue
<template>
  <b-list-group-item id="Todo">
    <b-row>
      <b-col md="8" :class="{isDone: this.todo.completed}">{{this.todo.text}}</b-col>
      <b-col md="2" class="pb-2">
        <b-button
          size="md"
          variant="primary"
          @click="toggleDone"
        >{{ this.todo.completed ? "unDone": "Done" }}</b-button>
      </b-col>
      <b-col md="2" class="pb-2">
        <b-button size="md" variant="primary" @click="$emit('remove-todo')">Delete</b-button>
      </b-col>
    </b-row>
  </b-list-group-item>
</template>

<script>
export default {
  name: "Todo",
  props: ["todo"],
  components: {},
  methods: {
    toggleDone() {
      this.todo.completed = !this.todo.completed;
    }
  }
};
</script>

<style>
.isDone {
  text-decoration: line-through;
}
</style>
