// angular-todo-app/src/app/todo/todo.component.ts
import { Component, Input, Output, OnChanges, EventEmitter } from '@angular/core';

import { Todo } from '../models/todo';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnChanges {
  @Input() todo: Todo;
  @Output() deleteTodo = new EventEmitter<number>();


  ngOnChanges() {
    console.log(this.todo);
  }

  onDone() {
    this.todo.completed = !this.todo.completed;
    console.log(this.todo);
  }

  onDelete() {
    this.deleteTodo.emit(this.todo.id);
  }

}

<div class="list-group-item">
  <div class="row w-100">

    <p class="col-md-9" [ngClass]="todo.completed ? 'isDone' : ''">{{todo.text}}</p>
    <button type="submit" class="btn btn-primary col mb-2 mx-2"
      (click)="onDone()">{{todo.completed ? "unDone" : "Done"}}</button>
    <button type="submit" class="btn btn-primary col mb-2 mx-2" (click)="onDelete()">Delete</button>
  </div>
</div>

// vue-todo-app/src/components/Todo.vue
<template>
  <b-list-group-item id="Todo">
    <b-row>
      <b-col md="8" :class="{isDone: this.todo.completed}">{{this.todo.text}}</b-col>
      <b-col md="2" class="pb-2">
        <b-button
          size="md"
          variant="primary"
          @click="toggleDone"
        >{{ this.todo.completed ? "unDone": "Done" }}</b-button>
      </b-col>
      <b-col md="2" class="pb-2">
        <b-button size="md" variant="primary" @click="$emit('remove-todo')">Delete</b-button>
      </b-col>
    </b-row>
  </b-list-group-item>
</template>

<script>
export default {
  name: "Todo",
  props: ["todo"],
  components: {},
  methods: {
    toggleDone() {
      this.todo.completed = !this.todo.completed;
    }
  }
};
</script>

<style>
.isDone {
  text-decoration: line-through;
}
</style>
